import { Processo } from "./models/curso";
import { MiniCurso } from "./models/mini-curso";

/**
 * @detalhesDosCursos
 * No momento, o projeto não busca as informações de processos seletivos abertos do servidor. 
 * Futuramente o administrador irá cadastrar os processos.
 * Estamos provisoriamente utilizando essa constante para obter as informações.
 */
export const detalhesDosCursos: Processo[] = [
    {
        idTeachable: 1785292, // id do teachable
        tipo: 'Martech Academy',
        turma: 'BC31',
        inicioBootcamp: '2022-08-15',
        inicioInscricoes: '',
        terminoInscricoes: '2022-08-08',
        status: 'Aberto',
        
    },
    {
        idTeachable: 1785292,
        tipo: 'Analista Midia Digital Performance', // tipo da url diferente em 'enviar video'
        turma: 'BC31',
        inicioBootcamp: '2022-08-15',
        inicioInscricoes: '',
        terminoInscricoes: '2022-08-08',
        status: 'Aberto',
    },
    {
        idTeachable: 1788757,
        tipo: 'Desenvolvedor Salesforce',
        turma: 'BC26',
        inicioBootcamp: '2022-07-04',
        inicioInscricoes: '',
        terminoInscricoes: '2022-06-22',
        status: 'Aberto',
    },
    {
        idTeachable: 1774608,
        tipo: 'Engenharia De Dados',
        turma: 'BC23',
        inicioBootcamp: '2022-06-23',
        inicioInscricoes: '',
        terminoInscricoes: '2022-06-13',
        status: 'Aberto',
    },
    {
        idTeachable: 1788844,
        tipo: 'Java Full Stack',
        turma: 'BC27',
        inicioBootcamp: '2022-07-18',
        inicioInscricoes: '',
        terminoInscricoes: '2022-07-08',
        status: 'Aberto',
        
    }
];

export const estadosDoBrasil: string[] = [
    'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'
];

export const niveisDeEscolaridade: string[] = [
    'Ensino Médio Incompleto',
    'Ensino Médio Completo',
    'Ensino Superior Incompleto',
    'Ensino Superior Completo',
    'Pós-graduação Incompleto',
    'Pós-graduação Completo',
    'Mestrado Incompleto',
    'Mestrado Completo'
];

export const areasDeFormacao: string[] = [
    'Ciências Exatas',
    'Ciências Humanas e Sociais',
    'Ciências Biológicas e de Saúde',
    'Não sei informar'
];

export const meiosDeContato: string[] = [
    'Facebook',
    'Instagram',
    'LinkedIn',
    'Twitter',
    'YouTube',
    'E-mail',
    'Imprensa/Notícias',
    'Pesquisa Online (Ex.: Google)',
    'Indicação',
    'Outro'
];

export const racasOuCores: Object[] = [
    {
        value: 'Branco',
        viewValue: 'Branco(a)'
    },
    {
        value: 'Preto',
        viewValue: 'Preto(a)'
    },
    {
        value: 'Pardo',
        viewValue: 'Pardo(a)'
    },
    {
        value: 'Amarelo',
        viewValue: 'Amarelo(a)'
    },
    {
        value: 'Indígena',
        viewValue: 'Indígena'
    },
    {
        value: 'Prefiro não informar',
        viewValue: 'Prefiro não informar'
    }
];

export const generos: string[] = [
    'Feminino',
    'Masculino',
    'Personalizado',
    'Prefiro não informar'
];

export const listaDeCursosGraduacao: string[] = [
    'Administração',
    'Agrimensura',
    'Agroecologia',
    'Agroindústria',
    'Agronomia (ou Engenharia Agronômica)',
    'Análise e Desenvolvimento de Sistemas',
    'Antropologia',
    'Aquacultura',
    'Arqueologia',
    'Arquitetura',
    'Arquivística',
    'Artes Cênicas',
    'Artes Visuais',
    'Astronomia',
    'Automação Industrial',
    'Biblioteconomia',
    'Biocombustíveis',
    'Bioengenharia',
    'Biofísica',
    'Biologia',
    'Biologia Marinha',
    'Biomedicina',
    'Biotecnologia',
    'Botânica',
    'Cafeicultura',
    'Ciência da Computação',
    'Ciência dos Alimentos',
    'Ciência dos Materiais',
    'Ciência e Tecnologia',
    'Ciência Política (ou Ciências do Estado)',
    'Ciências Aeronáuticas',
    'Ciências Agrárias',
    'Ciências Ambientais',
    'Ciências Atuariais',
    'Ciências Biológicas',
    'Ciências Biomoleculares',
    'Ciências Contábeis',
    'Ciências da Saúde',
    'Ciências do Meio Aquático',
    'Ciências Humanas (licenciatura)',
    'Ciências Matemáticas da Terra',
    'Ciências Naturais (licenciatura)',
    'Ciências Náuticas',
    'Ciências Sociais',
    'Cinema',
    'Comércio Exterior',
    'Comunicação social',
    'Construção de Edifícios',
    'Construção de Estradas',
    'Construção Naval',
    'Cooperativismo',
    'Cosmetologia',
    'Dança',
    'Defesa e Gestão Estratégica Internacional',
    'Desenho Industrial',
    'Design de Interiores',
    'Design de Jogos Digitais',
    'Design de Moda',
    'Design de Produto',
    'Design Gráfico',
    'Direito',
    'Drenagem e Irrigação',
    'Ecologia',
    'Economia',
    'Economia Doméstica',
    'Editoração',
    'Educação Artística (licenciatura)',
    'Educação do Campo (licenciatura)',
    'Educação física',
    'Energias Renováveis',
    'Enfermagem',
    'Engenharia Aeroespacial',
    'Engenharia Aeronáutica',
    'Engenharia Agrícola',
    'Engenharia Ambiental',
    'Engenharia Biomédica',
    'Engenharia Cartográfica (ou Engenharia Geográfica)',
    'Engenharia Civil',
    'Engenharia de Alimentos',
    'Engenharia de Computação',
    'Engenharia de Controle e Automação',
    'Engenharia de Manufatura',
    'Engenharia de Materiais',
    'Engenharia de Minas',
    'Engenharia de Pesca',
    'Engenharia de Petróleo',
    'Engenharia de Produção',
    'Engenharia de Sistemas Eletrônicos',
    'Engenharia de Software',
    'Engenharia de Tecidos',
    'Engenharia de Telecomunicações',
    'Engenharia Elétrica (ou Engenharia de Energia)',
    'Engenharia Física',
    'Engenharia Florestal',
    'Engenharia Geológica',
    'Engenharia Industrial Madeireira',
    'Engenharia Mecânica',
    'Engenharia Mecatrônica',
    'Engenharia Metalúrgica',
    'Engenharia Militar',
    'Engenharia Naval e Oceânica',
    'Engenharia Nuclear',
    'Engenharia Química',
    'Engenharia Sanitária',
    'Engenharia Têxtil',
    'Enologia',
    'Escultura',
    'Esporte e Lazer',
    'Estatística',
    'Eventos',
    'Farmácia (ou Bioquímica)',
    'Filosofia',
    'Física',
    'Física Computacional',
    'Física Médica',
    'Fisioterapia',
    'Fonoaudiologia',
    'Fotografia',
    'Fruticultura',
    'Gastronomia',
    'Geofísica',
    'Geografia',
    'Geologia',
    'Geoprocessamento e Sensoriamento Remoto',
    'Gerontologia',
    'Gestão Ambiental',
    'Gestão Comercial',
    'Gestão da Qualidade',
    'Gestão da Tecnologia da Informação',
    'Gestão de Petróleo e Gás',
    'Gestão de Recursos Hídricos',
    'Gestão de Segurança Privada',
    'Gestão do Agronegócio',
    'Gestão em Serviços Jurídicos e Notariais',
    'Gestão Financeira',
    'Gestão Hospitalar',
    'Gestão Portuária',
    'Gestão Pública',
    'Gravurismo',
    'História',
    'História da Arte',
    'Horticultura',
    'Hotelaria',
    'Informática',
    'Informática Biomédica',
    'Jornalismo',
    'Letras',
    'Linguística',
    'Logística',
    'Manutenção Industrial',
    'Matemática',
    'Matemática Aplicada',
    'Matemática Computacional',
    'Mecatrônica e Mecânica de Precisão',
    'Medicina',
    'Medicina Veterinária',
    'Meliponicultura',
    'Mercadologia',
    'Meteorologia',
    'Microbiologia e Imunologia',
    'Mineração',
    'Museologia',
    'Música',
    'Nanotecnologia',
    'Naturologia',
    'Negócios Imobiliários',
    'Neurociência',
    'Nutrição',
    'Oceanografia (arcaicamente referido como Ciência dos Mares)',
    'Odontologia',
    'Oftálmica',
    'Ordenamento do Território',
    'Paisagismo',
    'Pedagogia',
    'Pintura',
    'Processamento de Dados',
    'Processos Escolares',
    'Processos Metalúrgicos',
    'Produção Audiovisual (Rádio e TV ou Radialismo)',
    'Produção Cultural',
    'Produção de Aguardente',
    'Produção de Laticínios',
    'Produção de Materiais Plásticos',
    'Produção Fonográfica',
    'Produção Sucroalcooleira',
    'Produção Têxtil',
    'Projetos de Estruturas Aeronáuticas',
    'Psicologia',
    'Publicidade e Propaganda',
    'Química',
    'Química Ambiental',
    'Química Industrial',
    'Quiropraxia',
    'Radiologia',
    'Recursos Humanos',
    'Redes de Computadores',
    'Redes de Telecomunicações',
    'Relações Internacionais',
    'Relações Públicas',
    'Saneamento Ambiental',
    'Saúde Coletiva',
    'Secretariado',
    'Segurança da Informação',
    'Segurança no Trabalho',
    'Segurança Pública',
    'Serviço Social',
    'Silvicultura',
    'Sistemas Biomédicos',
    'Sistemas de Informação',
    'Sistemas de Navegação Fluvial',
    'Sistemas Elétricos',
    'Sistemas Embarcados',
    'Sistemas para Internet',
    'Sociologia',
    'Teatro',
    'Telemática',
    'Teologia',
    'Terapia ocupacional',
    'Transporte Aéreo',
    'Transporte Terrestre',
    'Turismologia',
    'Urbanismo',
    'Zootecnia',
  ];
